name: CI

on: [push, pull_request]

jobs:

  build:
    name: Create artifacts
    runs-on: ubuntu-latest

    steps:
      # Initialization
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - name: Copy configuration
        run: cp config.json.example config.json

      # Run linter
      - name: Lint
        run: npm run lint

      # Create Chrome artifacts
      - name: Create Chrome artifacts
        run: npm run build:chrome
      - uses: actions/upload-artifact@v4
        with:
          name: ChromeExtension
          path: dist
      - run: mkdir ./builds
      - uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        with:
          args: zip -qq -r ./builds/ChromeExtension.zip ./dist

      # Create Firefox artifacts
      - name: Create Firefox artifacts
        run: npm run build:firefox
      - uses: actions/upload-artifact@v4
        with:
          name: FirefoxExtension
          path: dist
      - uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        with:
          args: zip -qq -r ./builds/FirefoxExtension.zip ./dist

      # Create Safari artifacts
      - name: Create Safari artifacts
        run: npm run build:safari
      - uses: actions/upload-artifact@v4
        with:
          name: SafariExtension
          path: dist
      - uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        with:
          args: zip -qq -r ./builds/SafariExtension.zip ./dist
